name: "Setup DynamoDB for Terraform State Lock"

on:
  workflow_dispatch: # Run manually only once

permissions:
  id-token: write
  contents: read

jobs:
  create-dynamodb:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./dynamodb_setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: "Terraform-DynamoDB-Setup"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
